[package]
name = "did-plc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_ipld_dagcbor = "0.6"
k256 = "0.14.0-pre.2"
url = "2.5.4"
did-key = "0.2.1"
serde_json = "1.0.134"
base64 = "0.22.1"
base32 = "0.5.1"
sha2 = "0.11.0-pre.4"
chrono = "0.4.39"