[package]
name = "did-plc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_ipld_dagcbor = { workspace = true }
k256 = { workspace = true }
url = { workspace = true }
did-key = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
base32 = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
